throw clear Exception
khaled-alshamaa/ar-php pull request #10
Opened 2021-05-08 18:02 UTC by atmonshi

Throw an exception if the `$singular` is not **pre-defined** and `$plural` is not passed.

It gives a clear message about the issue instead of the default PHP `Undefined index` massage.

before:
![Screen Shot 2021-05-08 at 9 00 38 PM](https://user-images.githubusercontent.com/1952412/117548968-77d86d00-b040-11eb-8e7e-e5df934b4faf.png)

after:
![Screen Shot 2021-05-08 at 9 00 25 PM](https://user-images.githubusercontent.com/1952412/117548967-773fd680-b040-11eb-9d5b-d92c5d2dd729.png)

2021-05-10 04:55 UTC, atmonshi commented
I switched this to a draft since I notice there are so many checks in other functions.

My point is since this package for developers. I think it's a better experience to deliver better error handling.
Especially in cases where the function had optional parameters, but it's required in some cases.
as in

```php
function arPlural($singular, $count, $plural2 = null, $plural3 = null, $plural4 = null)
```

If you agree to the concept, I will continue adding the necessary checks and reopen this PR.

2021-06-19 20:41 UTC, khaled-alshamaa commented on src/Arabic.php
> +     * @return string|\Exception Proper plural form of the given singular form, throw exiption if the $singular is not pre defiend and $plural is not passed
`@return` tag in the phpdoc should stay as it is, and exceptions should be documented using the  `@throws` tag instead. For more information, please check this reference:
https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/throws.html

2021-06-19 20:54 UTC, khaled-alshamaa commented on src/Arabic.php
> +        if(!array_key_exists($singular, $this->arPluralsForms)){
This condition with throw an exception even if the developer passing the plural forms in explicit way (i.e. plural2, plural3, and plural4). Instead, I believe it should be something like this:
`if(!array_key_exists($singular, $this->arPluralsForms) && (is_null($plural2) || is_null($plural3) || is_null($plural4))){`

2021-06-19 21:01 UTC, khaled-alshamaa commented on src/Arabic.php
> +            throw new \Exception("Please Provide all plural forms for the word: $singular.");
Why you used `\Exception` instead of simply `Exception`?

2021-06-19 21:08 UTC, khaled-alshamaa requested changes
What if we take it one step further and extends the general Exception class like this?
`class ArphpException extends Exception { }`

2021-07-13 23:07 UTC, khaled-alshamaa commented
No action taken by @atmonshi

2021-07-13 23:07 UTC, closed without merging